// Generated by Timber
// this file should not be touched by user directly
#include <abct/AbcTRuntime.hpp>

class Container {
public:

std::vector<int> data;
Container(std::vector<int> input)  {
  data = input;
 }
int size() const { return getLength(data);
}
int __getElement__(int index) const { return data[index];
}
};

int main() { Container c = Container({10, 20, 30, 40});
 auto it = iterate(c);
 while (!done(it)) {
  print(next(it));
 }
 reiterate(it);
 while (!done(it)) {
  print(next(it));
 }
 return 0;
}