// Generated by Timber
// this file should not be touched by user directly
#include <abct/AbcTIO.hpp>

int main() { std::vector<std::vector<int>> matrix = {{10, 20}, {30, 40}, {50, 60}};
 print("--- Running Matrix Scale (While Loop) ---");
 int row;
 row = 0;
 while (row < 3) {
  int col;
  col = 0;
  while (col < 2) {
   matrix[row][col] = matrix[row][col] +  5;
   col = col +  1;
  }
  row = row +  1;
 }
 print(matrix);
 print("--- Running Accumulator Target Check ---");
 int sum;
 sum = 0;
 int i;
 i = 0;
 while (i < 3) {
  int current_val;
  current_val = matrix[i][0];
  if (sum +  current_val < 150) {
   sum = sum +  current_val;
   print(sum);
  }
  i = i +  1;
 }
 return 0;
}