// Generated by Timber
// this file should not be touched by user directly
#include <abct/AbcTIO.hpp>

int main() { std::vector<std::vector<int>> grid = {{45, 89, 12}, {73, 34, 95}, {18, 62, 50}};
 print("--- Original Sensor Grid ---");
 print(grid);
 print("--- Flagged High-Value Coordinates ---");
 int r;
 r = 0;
 while (r < 3) {
  int c;
  c = 0;
  while (c < 3) {
   int val;
   val = grid[r][c];
   if (val > 60) {
    print("Alert at coordinate:");
    print(r);
    print(c);
    print("Value:");
    print(val);
   }
   c = c +  1;
  }
  r = r +  1;
 }
 return 0;
}