// Generated by Timber
// this file should not be touched by user directly
#include "abct/AbcTTypes.h"

template <typename T_M_HASHABLE>

using T = T_M_HASHABLE;
class container {
public:
 T val;
 template <typename U_M_ANY>
 using U = U_M_ANY;
 int process(U_M_ANY input) {
  return 0;
 }
};

class integer {
public:
 CompileTimeConst __traits__ = {"Integral"};
private:
 long x;
};

int main() {
 container value = {1, 2};
 return 0;
}