// Generated by Timber
// this file should not be touched by user directly
#include <abct/AbcTRuntime.hpp>

template <typename T_M_HASHABLE>
class container {
public:

container(T_M_HASHABLE input) { data = input;
}
private:

T_M_HASHABLE data;
};

int main() { container<std::string> MyData = container("data");
 return 0;
}